/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TasksTaskIdImport } from './routes/tasks/$taskId'

// Create Virtual Routes

const RegisterLazyImport = createFileRoute('/register')()
const LoginLazyImport = createFileRoute('/login')()
const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()
const TasksUpcomingLazyImport = createFileRoute('/tasks/upcoming')()
const TasksTodayLazyImport = createFileRoute('/tasks/today')()

// Create/Update Routes

const RegisterLazyRoute = RegisterLazyImport.update({
  path: '/register',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/register.lazy').then((d) => d.Route))

const LoginLazyRoute = LoginLazyImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const TasksUpcomingLazyRoute = TasksUpcomingLazyImport.update({
  path: '/tasks/upcoming',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/tasks/upcoming.lazy').then((d) => d.Route),
)

const TasksTodayLazyRoute = TasksTodayLazyImport.update({
  path: '/tasks/today',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/tasks/today.lazy').then((d) => d.Route))

const TasksTaskIdRoute = TasksTaskIdImport.update({
  path: '/tasks/$taskId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginLazyImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      preLoaderRoute: typeof RegisterLazyImport
      parentRoute: typeof rootRoute
    }
    '/tasks/$taskId': {
      preLoaderRoute: typeof TasksTaskIdImport
      parentRoute: typeof rootRoute
    }
    '/tasks/today': {
      preLoaderRoute: typeof TasksTodayLazyImport
      parentRoute: typeof rootRoute
    }
    '/tasks/upcoming': {
      preLoaderRoute: typeof TasksUpcomingLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  AboutLazyRoute,
  LoginLazyRoute,
  RegisterLazyRoute,
  TasksTaskIdRoute,
  TasksTodayLazyRoute,
  TasksUpcomingLazyRoute,
])

/* prettier-ignore-end */
